Graphics.prototype.setFontRobotoRegular1 = function () {
  // Actual height 16 (15 - 0)
  // 1 BPP
  return this.setFontCustom(
    atob(
      "AAAAAAAAAAAAAH+Qf9B/0AAAYAB4AHgAeAB4AHgAAAAEsAfwf+B8kAfwf/B+gESAAAA4YHxwfjD/+P/4Y/Bx8DHgAAA8AH4AfhB+MH7gPcAHAA4APeBz8GMwQ/AD8AAAAOAB8BPwfzB/kG/wf/B88DfwBxAGMAQwAAB4AHgAYAAAAAfgH/g//HAOYAYAAGAGcA4+fB/4D/AAACQAPAA8AH4AfgA8ADwAJAAAAAIAAgACAD/gP+A/4AIAAgACAAAAABQAFAAcABgAAACAAIAAgACAAIAAAAAQABAAEAAQAAAA8APwH4B8AAAAH8A/4H/wYDBgMH/wP+AfwAAAAAAgEGAQf/B/8H/wABAAADAQcDBgcEDQd5B/ED4wADAAADAQcBBiEEYQf7B/8DPgAAABgAeADoA4gH/wf/B/8ACAAAAAEBgQeBBsEE4wR/BD4AAAB8Af4D/wPjBmEGfwR+BDwAAAMABwAEAQQfBP8H+AfABgAAAAGGA98H/wbzBHEH/wPfAQ4AAAHhA/EH8wQzBh4H/gP8AfAAAAAAAEEAQQBBAAAAAQBBQEHAQcAAACAAcABQAFgAyACIAIwBhAEEAAAASABIAEgASABIAEgASABIAEgAAAEEAYQAjACIAMgAWABQAHAAIAAAAwAHAAUBBD0H+QfgA4AAAAA/AP+B4eOOYz82fzTxFMcUnxT/Fv0342Pe4f3AIQAAAAMADwA/AfkH6AeIB/kD/QB/AA8AAwABAAAEAQf/B/8H/wQhBCEGcwf/A98BngAAAPgD/gP+BwcGAwQBBAEGAweHB4YAhAAABAEH/wf/B/8EAQQBBgMHBwf/A/4B/ABwAAAEAQf/B/8H/wQhBCEE+Qb7BgcABgAABAEH/wf/B/8EIQT4BPgGAAYAAAAA+AH+A/4HDwYDBAEEIQYhBz8HPwM+ACAAAAQBB/8H/wf/BCEAIAQhBCEH/wf/B/8EAQAABAEH/wf/B/8EAQAAAAMEAwf/B/8H/gQAAAAEAQf/B/8H/wR5APgFnQcPBgcEAwQDAAEAAAQBB/8H/wf/BAEEAQABAAMABwAEAAAEAQf/B/8H4QP5AP4APwAfAH4B8Qf/B/8H/wQBAAAEAQf/B/8HgQPBAfAAeAQ8B/8H/wf/BAAAAAD4A/4D/gcHBgMEAQQBBgMH/wP+AfwAcAAABAEH/wf/B/8EEQYwB/AD8AHgAAAA+AP+A/4HBwYDhAGEAcYDx/9j/mH8IHAgAAQBB/8H/wf/BDEGfAf+B88DxwADAAEAAAGPB88H5wbjBHEGOwc/Bx4ADAAABwAHAAQBB/8H/wf/BAEEAQcABwAAAAQAB/4H/gf/BAMAAQABBAMH/wf+B/gEAAAABAAHAAfAB/gE/gA/AA8EPgf4B8AGAAQAAAAEAAcAB/AH/gR/BA8H/wf4B/4E/wAfBH8H+AfABgAAAAQBBgMHBwfPB/0E+AD9Bf8HjwcHBgMEAQAABAAGAAcAB8EF/wT/AH8F4QfBBwAGAAQAAAABAwcHBh8EPQT5BfEHwQeDBgcEBwAAAAAH/+f/5//kACAAB4AH8AD+AB8AAAQAJAAn/+f/5//gAABgAeAHwAcABwADwADgACAAAAAAIAAgACAAIAAgACAAIAAgAAQABgAHAAMAAAAAJwBvAG8AWQB/AH8APwAAB/4H/wf/AGMAQQB/AH4APgAAAD4AfwB/AEEAYQBjACMAAAAeAH8AfwBDAmMH/wf/B/8AAAA+AH8AfwBTAHEAcwAzAAAAQQH/A/8H/wRBAAAAMuB/4H/gTSB9IH0geeBBwAAH/wf/B/8AYQBBAH8AfwA/AAAAIQR/BH8EfwAAACAkf+R/5H+AAAf/B/8H/wAdAH8AZwBDAEEAAAIBB/8H/wf/AAAAfwB/AH8AYQBBAH8AfwB/AGEAfwB/AD8AAAB/AH8AfwBhAEEAfwB/AD8AAAA+AH8AfwBDAGEAfwB/AD4AAAA/4H/gf+BjIEEAfwB/AD4AAAA+AD8AfwBBAGEgf+B/4H/gAAB/AH8AfwBhAEAAAAAzAHsAeQBtAG8AZwAAAHwB/wH/AEMAAAB8AH8AfwADAEMAfwB/AH8AAABAAHAAfgBfAAcAXwB4AEAAAABAAHgAfwBfAE8AfgB+AH8ADwB/AHgAQAAAAEMAZwB/AH0AfwBvAGcAQwAAAEAgeCB+YF/gD8B+AHgAQAAAAGMAZwBPAF8AeQBzAGMAAAAAABAAOAP/x+/nx+QAIAAH//f/9//wAAAABAAnx+fv4//AOAAQAAAAGAAYABAAGAAYAAgACAAYABgAAA"
    ),
    32,
    atob(
      "BAUHCQkODQQGBgkKBQYFBQkICQgJCAkJCQkFBQoKCggQDQsMDQsKDQ0GBw0LDw0NCg0MCgsNDRANDQsGBQYJCQUICQgJCAYJCQUFCQUNCQkJCQYHBQkJDQkJCAgECAo="
    ),
    16 | 65536
  );
};
